-- EHA Command Bots - Seed Data
-- Initial data to populate the database

-- Insert Officer Roles
INSERT INTO officers (name, rank, role, personality_prompt_file, status) VALUES
('Commander Hayes', 'Commander', 'commander', 'prompts/officer-personalities/commander.md', 'active'),
('Lt. Commander Chen', 'Lieutenant Commander', 'xo', 'prompts/officer-personalities/xo.md', 'active'),
('Lt. Rodriguez', 'Lieutenant', 'intelligence', 'prompts/officer-personalities/intelligence-officer.md', 'active'),
('Major Barrett', 'Major', 'operations', 'prompts/officer-personalities/operations-officer.md', 'active'),
('Captain Morrison', 'Captain', 'logistics', 'prompts/officer-personalities/logistics-officer.md', 'active'),
('Lt. Singh', 'Lieutenant', 'communications', 'prompts/officer-personalities/comms-officer.md', 'active');

-- Insert a sample story arc for testing
INSERT INTO story_arcs (title, description, start_date, status, difficulty_level) VALUES
('The Vanaar Incursion',
'An unknown alien force, the Vanaar, has begun probing the outer colonies. Intelligence suggests they are testing our defenses before a larger assault. The organization must investigate their intentions, defend key installations, and prepare for potential full-scale conflict.',
datetime('now'),
'planning',
6);

-- Insert sample story state for the arc
INSERT INTO story_state (story_arc_id, state_key, state_value, value_type) VALUES
(1, 'vanaar_threat_level', '3', 'number'),
(1, 'colonies_under_threat', '["Outpost Delta", "Mining Station Zeta"]', 'json'),
(1, 'first_contact_made', 'false', 'boolean'),
(1, 'intel_gathered', '15', 'number');

-- Insert a sample initial event
INSERT INTO story_events (story_arc_id, event_title, event_description, event_type, impact_level) VALUES
(1, 'First Vanaar Sighting',
'Long-range sensors detected an unknown vessel signature near the Outer Rim. Initial analysis suggests advanced propulsion technology unlike any known faction.',
'plot_point',
7);

-- Note: Players will be added dynamically as Discord users interact with the bot
-- Note: Missions will be generated by the AI officers through n8n workflows
