-- EHA Command Bots - Seed Data
-- Initial data to populate the database

-- Insert AI Officer Roles (aligned with EHA structure)
INSERT INTO officers (name, rank, role, personality_prompt_file, status) VALUES
-- High Command (Story Authority)
('General Vance', 'General', 'commander', 'prompts/officer-personalities/fleet-commander.md', 'active'),

-- Division Support Officers (Tactical/Operational)
('Lt. Colonel Morrison', 'Lieutenant Colonel', 'logistics', 'prompts/officer-personalities/logistics-operations.md', 'active'),
('Lt. Colonel Van Der Merwe', 'Lieutenant Colonel', 'operations', 'prompts/officer-personalities/tactical-operations.md', 'active'),
('Lt. Colonel Reeves', 'Lieutenant Colonel', 'operations', 'prompts/officer-personalities/flight-operations.md', 'active'),

-- Specialized Staff Officers (Cross-Division Support)
('Lt. Colonel Singh', 'Lieutenant Colonel', 'intelligence', 'prompts/officer-personalities/intelligence-officer.md', 'active'),
('Major Chen', 'Major', 'communications', 'prompts/officer-personalities/communications-officer.md', 'active');

-- Insert Real EHA Commanders (for reference and coordination)
-- Note: These are not AI - they represent the real commanders
INSERT INTO officers (name, rank, role, personality_prompt_file, status) VALUES
('Commander Atlay', 'Commander', 'commander', NULL, 'active'),
('Commander Hunter', 'Commander', 'commander', NULL, 'active');
-- Commander for Alpha Squad position vacant (Psykes resigned)

-- Insert a sample story arc for testing (Star Citizen themed)
INSERT INTO story_arcs (title, description, start_date, status, difficulty_level) VALUES
('Operation: Crimson Dawn',
'A series of coordinated pirate attacks have disrupted trade routes in the Stanton system. Intelligence suggests these raids are more organized than typical pirate activity, possibly backed by a rival PMC or criminal syndicate. EHA has been contracted to investigate, secure the trade lanes, and eliminate the threat. All three divisions - Nexus, Morozov, and Alpha Squad - will be deployed in coordinated operations.',
CURRENT_TIMESTAMP,
'planning',
6);

-- Insert sample story state for the arc
INSERT INTO story_state (story_arc_id, state_key, state_value, value_type) VALUES
(1, 'pirate_threat_level', '4', 'number'),
(1, 'trade_routes_affected', '["Crusader-ArcCorp", "MicroTech-Hurston"]', 'json'),
(1, 'intel_confidence', 'medium', 'string'),
(1, 'civilian_casualties', '12', 'number'),
(1, 'contract_value_uec', '2500000', 'number');

-- Insert a sample initial event
INSERT INTO story_events (story_arc_id, event_title, event_description, event_type, impact_level) VALUES
(1, 'Coordinated Strike on Convoy',
'Three cargo haulers escorted by hired security were ambushed near Crusader. Attackers displayed unusual coordination and advanced tactics. Two haulers destroyed, one captured. Security forces report attackers used military-grade weapons and communications. General Vance has convened an emergency briefing.',
'plot_point',
8);

-- Note: Players will be added dynamically as Discord users interact with the bot
-- Note: Missions will be generated by the AI officers through n8n workflows
-- Note: Real commanders (Atlay, Hunter) issue orders through their human agency
